name: aveomap
description: A new Flutter package project.
version: 0.0.1
homepage: null

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.2.1
  custom_info_window: ^1.0.1
  flutter:
    sdk: flutter
  geocoding: ^2.0.4
  geolocator: ^10.1.0
  get: ^4.6.5
  google_maps_flutter: ^2.1.9
  map_launcher: ^2.2.3
  uuid: ^4.2.2
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

  
flutter:
  uses-material-design: true
  assets:
    - assets/apple_map.png
